name: "DRS PR Reviewer AI"
description: "DRS-LLM 기반으로 GitHub Pull Request의 위험도를 분석하고 자동 리뷰 코멘트를 남깁니다."
author: "YOUR_NAME_OR_ORG"

inputs:
  drs-api-base-url:
    description: "DRS-LLM HTTP API Base URL (예: https://your-drs-server/drs-api)"
    required: false
  drs-api-token:
    description: "DRS-LLM API 인증 토큰 (선택)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Build
      run: npm run build
      shell: bash

    - name: Run DRS PR review
      run: npm run drs:review
      shell: bash
      env:
        # GITHUB_TOKEN 은 워크플로우에서 env 로 주입된 값을 그대로 사용
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        # DRS API 설정은 inputs 를 통해 주입
        DRS_API_BASE_URL: ${{ inputs.drs-api-base-url }}
        DRS_API_TOKEN: ${{ inputs.drs-api-token }}

branding:
  icon: "shield"
  color: "purple"

